/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi_cuti;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import java.awt.event.KeyEvent;
/**
 *
 * @author user
 */
public class Aplikasi_Ganti_Password extends javax.swing.JFrame {
koneksi kon = new koneksi();
    /**
     * Creates new form Aplikasi_Ganti_Password
     */
    public Aplikasi_Ganti_Password() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/gambar/Eiger.png");
        setIconImage(ico.getImage());
        kon.setKoneksi();
    }
    public String Kode_User;
    public String getKodeUser()
    {
        return Kode_User;
    }
    
    void nonaktif()
    {
        tKode_user.setEnabled(false);
        tpassLama.setEnabled(false);
        tpassBaru.setEnabled(false);
        tkonfirmPass.setEnabled(false);
    }
    
    void bersih()
    {
        tpassLama.setText("");
        tpassBaru.setText("");
        tkonfirmPass.setText("");
    }
    
private void passlama()
{
    try{
        String sql = "Select *from user where password=" + tpassLama.getText();
                kon.rs = kon.st.executeQuery(sql);
                if(kon.rs.next()){
                    
                    tpassBaru.setEnabled(true);
                    tpassBaru.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "Kode User tidak ada, Silahkan"
                             + " Isi Data");
                    tpassLama.requestFocus();
                }
    
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
    }

private void konfirmpassword()
{
    try{
        if(tkonfirmPass.getText().equals(tpassBaru.getText()))
        {
            String sql = " update user set password='" + tkonfirmPass.getText()
                    + "' where kd_user='" + tKode_user.getText() + "'";
            kon.st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Password telah terupdate");
            nonaktif();
            bersih();
        }
        else {
            JOptionPane.showMessageDialog(null, "Password baru dan konfirmasi " 
                    + "password harus sama");
            nonaktif();
            bersih();
        }
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }

}        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tKode_user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tpassLama = new javax.swing.JPasswordField();
        tpassBaru = new javax.swing.JPasswordField();
        tkonfirmPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Ganti Password");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 44, -1, -1));

        jLabel2.setText("Password Lama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 72, -1, -1));

        jLabel3.setText("Password Baru");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 110, -1, -1));

        jLabel4.setText("Konfirmasi Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 133, -1, -1));

        tKode_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKode_userActionPerformed(evt);
            }
        });
        getContentPane().add(tKode_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 38, 50, -1));

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        tpassLama.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tpassLamaComponentResized(evt);
            }
        });
        tpassLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassLamaActionPerformed(evt);
            }
        });
        getContentPane().add(tpassLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, -1));

        tpassBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassBaruActionPerformed(evt);
            }
        });
        getContentPane().add(tpassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        tkonfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkonfirmPassActionPerformed(evt);
            }
        });
        tkonfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tkonfirmPassKeyPressed(evt);
            }
        });
        getContentPane().add(tkonfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void tKode_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKode_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKode_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tKode_user.setText(Kode_User);
        nonaktif();
        tpassLama.setEnabled(true);
    }//GEN-LAST:event_formWindowActivated

    private void tpassLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassLamaActionPerformed
        // TODO add your handling code here:
        passlama();
    }//GEN-LAST:event_tpassLamaActionPerformed

    private void tpassBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassBaruActionPerformed
        // TODO add your handling code here:
        tkonfirmPass.setEnabled(true);
        tkonfirmPass.requestFocus();
    }//GEN-LAST:event_tpassBaruActionPerformed

    private void tkonfirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkonfirmPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            konfirmpassword();
        }
    }//GEN-LAST:event_tkonfirmPassKeyPressed

    private void tkonfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkonfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkonfirmPassActionPerformed

    private void tpassLamaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tpassLamaComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassLamaComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Ganti_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Ganti_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Ganti_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Ganti_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi_Ganti_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tKode_user;
    private javax.swing.JPasswordField tkonfirmPass;
    private javax.swing.JPasswordField tpassBaru;
    private javax.swing.JPasswordField tpassLama;
    // End of variables declaration//GEN-END:variables
}
